# Generated by Django 3.2.6 on 2021-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
